server:
  port: 0
  servlet:
    context-path: /news
eureka:
  client:
    service-url:
      defaultZone: http://server:8761/eureka

spring:
  datasource:
    url: jdbc:postgresql://news-comment-db:5432/news_management
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    clear-check-sums: true
    url: jdbc:postgresql://news-comment-db:5432/news_management
    user: username
    password: password
    driver-class-name: org.postgresql.Driver
    contexts: dev
springdoc:
  swagger-ui:
    path: /swagger-ui.html
